spring.application.name=seaside

server.port=8080
server.error.include-message=always

#datasource
spring.jpa.database=h2
spring.datasource.driver-class-name=org.h2.Driver
#nombre base de datos
spring.datasource.url=jdbc:h2:mem:mydatabase
spring.datasource.username=sa
spring.datasource.password=

#consola de administracion de h2
spring.h2.console.enabled=true
#localhost:8080/h2
spring.h2.console.path=/h2
spring.h2.console.settings.web-allow-others=true
spring.sql.init.mode=always

# Datos de prueba
spring.jpa.generate-ddl=true
#borrar la tabla cada vez
spring.jpa.hibernate.ddl-auto=create-drop
#spring.sql.init.mode=

# Logging
#permite imprimir la query
logging.level.org.hibernate.SQL=DEBUG
#imprime los parametros de las querys
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# pasarela de pagos - mercado pago
mercadopago.access_token=APP_USR-2733717436912311-052501-710b0dd6cd71072f349f4d0ea0476f17-3423210037
